<?php

namespace Huytt\User\Providers;

use Huytt\Core\Providers\CoreModuleServiceProvider;
use Huytt\User\Models\User;

class ModuleServiceProvider extends CoreModuleServiceProvider
{
    protected $models = [
        User::class
    ];

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->register(UserServiceProvider::class);
    }
}
