<?php

namespace Huytt\Loan\Providers;

use Huytt\Core\Providers\CoreModuleServiceProvider;
use Huytt\Loan\Models\Loan;
use Huytt\Loan\Models\ScheduledPayment;

class ModuleServiceProvider extends CoreModuleServiceProvider
{
    protected $models = [
        Loan::class,
        ScheduledPayment::class
    ];

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->register(LoanServiceProvider::class);
    }
}
