<?php

namespace Huytt\Core\Providers;

use Konekt\Concord\BaseModuleServiceProvider;

class ModuleServiceProvider extends CoreModuleServiceProvider
{
    protected $models = [
    ];

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->register(CoreServiceProvider::class);
    }
}
