<?php

namespace Huytt\Admin\Providers;

use Huytt\Admin\Models\Admin;
use Huytt\Core\Providers\CoreModuleServiceProvider;

class ModuleServiceProvider extends CoreModuleServiceProvider
{
    protected $models = [
        Admin::class,
    ];

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->register(AdminServiceProvider::class);
    }
}
