<?php

namespace Huytt\Admin\Tests\Unit;

use Huytt\Admin\Repositories\AdminUserRepository;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AdminTest extends TestCase
{
    use DatabaseTransactions, WithFaker;

    /** @var AdminUserRepository */
    protected $repository;

    protected $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = new AdminUserRepository($this->app);
        $this->setUpFaker();
    }

    public function testRegister()
    {
        $payload = [
            "name" => $this->faker->name,
            "email" => $this->faker->email,
            "password" => $this->faker->password
        ];

        $reponse = $this
            ->json('post', 'api/v1/admin/register', $payload);

//        echo json_encode($reponse)."\n";
        $reponse->assertStatus(201);
        $id = $reponse->decodeResponseJson()['data']['id'];
        $user = $this->repository->find($id);
        $this->assertEquals($payload['name'], $user->name);
        $this->assertEquals($payload['email'], $user->email);

        return array_merge($payload, ['id' => $id]);
    }
}
